### ISSUE TITLE
Caching Mechanism for Definitions

### ISSUE THREAD

**Issue by erikkanderson** [shooterstech/BabelFish#9]
Reconfigurable Rulebook Definitions rarely change. Some of them may go weeks or months before a definition changes. Which means they are a good candidate for caching. This enhancement is to develop a 2 tier caching mechanism for definitions. 

- [ ] The basic algorithm should be when a call is made to GetDefinition():

1. Check local memory for a copy of the definition. If available, return it. 
   * Track the last updated time for the definition. If it gets too old, then try and get a fresh copy of the definition.
2. Check the local file system to see if a cached copy of the definition. If available, return it.
    * Track the last updated time for the definition (possibly based on file write time). If it is too old, compare the version number of the definition file compared to the version number that's on the server. If a newer version is available, download it, save it, and return it. If a newer version is not available, return the definition already stored in the filesystem. 
    * If the local definition file is corrupted or can't be read for any reason, download it and return the new version.

Additional Requirements:

- [ ] Allow the caller to bypass the caching and always return what is available on the server. 
- [ ] Allow the caller to specify the how-old-is-too-old values for cached copies, both for in memory and file based. 
- [ ] Through a configuration file set the default how-old-is-too-old values.

An example of how to implement most of this may be found in the Orion repository, under Medea/WebServices/DefinitionManager.cs, in the TryLoad() function. What this implement does not do is 1) Check the version number on the server or 2) Use a file based configuration file for setting the how-old-is-too-old value. 

A few notes about checking the version number. 

 - To learn the version number on the server, call the GetDefinition API with the added parameter version=true. What gets returned is the SetName, Type, and Version. The definition is not included. 
 - If the SetName's version value is of the form vN.M, where M is not 0, then you never have to check. When .M is 0, it means to pull the latest version.

**Comment by erikkanderson** [comment]
See https://support.orionscoringsystem.com/index.html?definition-versioning.html for more information on SetName versioning.

**Comment by adam-shooterstech** [comment]
Created branch to continue Definition Cache work.

**Comment by adam-shooterstech** [comment]
Code completed and tested. Pushed to github and Pull Request generated for review.

Definition Cache in local memory/file system ready for review.
I believe all the requirements were achieved.
Please reach out if you want a walk-through the code or find any problems or want anything refactored.

All this is transparent to the user except for the new UserSettings passed in to control DefinitionCache functionality.

Unit Tests created for functionality. ATTRIBUTE, COURSEOFFIRE tests for different types saved to memory/file.
Confirmed GetReconfigurableRulebookDefinitionTests successfully save Definitions as they use the same function call.
Default directory: uses UserSettings(below) if set, otherwise first checks for user's Orion My Matches dir then fails over to user's temp dir, storing them in a DEFINITIONS sub directory by SetName.filename.
New UserSettings are:
Definitions_CacheIgnore(true/false, default=false if absent)
Definitions_CacheExpireTime(int for days, default=14 if absent)
Definitions_CacheStorageDirctory(string of preferred storage directory, default noted above)

**Comment by adam-shooterstech** [comment]
Addressed path errors Dr. Anderson discovered.
Update default cache directory logic + fix UnitTest to follow default cache directory path
